### ISSUE TITLE
Discussion about maths.

### ISSUE THREAD

**Issue by cheako** [dbr/imgui-docking-rs#1]
Where can I go to chat about imgui?  I have this issue where I don't understand scaling, years ago I brute forced [this](https://gitlab.com/cheako/ash-tray-rs/-/blob/f4471315348a6a6959e4689b9b37b7639fc3fb59/src/imguiash.rs#L703) and I never understood where this came from.  Now I'm on a High DPI, there are a lot of pixels at this distance per radian making things angularly small, display and I'm trying to scale up the GUI.

I'm looking for the equations imgui uses, so I'm not brute-forcing things.

**Comment by dbr** [comment]
imgui-rs is pretty direct bindings to the C++ library, so the details of all of the drawing code will be in https://github.com/ocornut/imgui/ - most probably in `imgui_draw.cpp` - there is also a discussion board on the imgui project if you have any specific questions

I'll close this, and archive this fork (as mentioned in #3 this was a temporary fork while I worked on merging the docking branch functionality into the main imgui-rs repo, which is now done) - I meant to archive it ages ago, but forgot this repo was still around!
