### ISSUE TITLE
Floating windows?

### ISSUE THREAD

**Issue by cheako** [dbr/imgui-docking-rs#2]
Per this video: https://www.youtube.com/watch?v=UljMVrQ_zYY floating windows just happens, but I'm looking for documentation or anything because I believe I would need to write the code to tell winit to make and destroy windows?

**Comment by dbr** [comment]
This requires a bunch of additions to the renderer and platform-support modules (e.g imgui-glow-renderer and imgui-winit-support or whatever you are using), and is relatively complicated compared to the single window code

Someone has started on this here: https://github.com/imgui-rs/imgui-rs/pull/619
